name: sample_exception
description: Define a generic exception for all project and library. help the Developer code easer with error and exception.
version: 1.0.0+4
repository: https://github.com/sonnts996/sample_exception

environment:
  sdk: '>=2.12.1 <3.0.0'
  reflectable: ^3.0.7

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
